### ISSUE TITLE
Add locations to upcoming events list

### ISSUE THREAD

**Issue by megandalster** [megandalster/PQG-Website#1]

**Comment by megandalster** [comment]
Location now shows on the featured next members meeting on the home page, but not on all the future events in the list on the right.  If you click any of those on the right, you'll see the location.  Is that sufficient?  If not, I'm afraid it will cost some money to add that functionality.

**Comment by lynn-gavett** [comment]
It proably is not worth spending any money to add the locations in the Upcoming Events box, however, they still do not look "clickable".  Traditionally, text in blue looks like a link to click.  Would that help?

**Comment by megandalster** [comment]
I have changed the link text to blue when you hover the mouse over it.  Seems to help them look more "clickable."  Fixing the background color may also help fix this issue.
