### ISSUE TITLE
Upoming Events

### ISSUE THREAD

**Issue by lynn-gavett** [megandalster/PQG-Website#10]
The Upcoming Events column should only appear on the right of the Home page.  Not on every page.

**Comment by megandalster** [comment]
This column now appears only on the Home page and the News page.  All other pages are full width.  (It is tricky to remove it from the News page, so let me know if that is okay.)

**Comment by megandalster** [comment]
We cannot easily change the font and font size in the Upcoming Events box without paying money for the premium version of that module.  How important is this?
