### ISSUE TITLE
Website on IPad 

### ISSUE THREAD

**Issue by lynn-gavett** [megandalster/PQG-Website#11]
When I open the website on my iPad, there is no photo slider?

**Comment by lynn-gavett** [comment]
Also, Menu does not open.

**Comment by megandalster** [comment]
I tried it on Meg's iPhone and it seems okay.  Maybe since I made the slider full width, it will now work on your iPad?  

Also, the menu should open as a black box on the right.  That seems to work on Meg's iPhone.

**Comment by lynn-gavett** [comment]
Menu now opens on right, however, no photo slider on IPad.  I get photos and menu on my phone.

**Comment by megandalster** [comment]
Try this again.  I've reworked the slider altogether.
