### ISSUE TITLE
Home Page - Facebook

### ISSUE THREAD

**Issue by lynn-gavett** [megandalster/PQG-Website#14]
Please move the copy about the Guild into the Copyright box.  Also, include Facebook info.  The box should be able to be outlined in a color or filled with a color.

**Comment by megandalster** [comment]
The facebook link is in the upper right corner and the lower right corner.  The copy about the Guild is moved to the copyright box.  I haven't figured out yet how to color this box.

**Comment by lynn-gavett** [comment]
The Facebook link needs to be more visable.  Can we have a more obvious Facebook logo, and our Facebook page, similar to our old site?  It only needs to be at the bottom of the page.

**Comment by lynn-gavett** [comment]
Facebook link missing?

**Comment by megandalster** [comment]
I've added it to the right-hand menu on the home page.
