### ISSUE TITLE
Delete News Page

### ISSUE THREAD

**Issue by lynn-gavett** [megandalster/PQG-Website#16]
Please delete the News Page, and add a Program & Workshop page.  We want the members to be able to sign up for workshops online, so we need a link to the Workshop Registration form.  The Public will need to email Palmettoquiltguild@gmail.com for more information.

**Comment by megandalster** [comment]
The registration form should be attached to each workshop when you create it.  Take a look at the September workshop for an example.

**Comment by megandalster** [comment]
The new Programs & Workshops page now shows the next upcoming workshop, along with a Workshop Registration form.  I've also added a new Editor Help instruction for creating future workshops like this one.  Take a look and try it out on, say, the October workshop. Let me know if you have questions about adding photos, the registration form, or anything else.

**Comment by lynn-gavett** [comment]
We have set up a new process for signing up for 2017 workshops.  Meg can show you in the September newsletter.  There is a date and time when sign up will begin for each workshop.  Can you set time and date restriction, so no workshop registration form can be sent before that time and date?

**Comment by megandalster** [comment]
The workshop signup form is now printable, so signing up will be a completely paper process, with forms mailed in to the workshop organizer.  So she can set the dates and times for signups on the workshop blurb on the website, but she can enforce them independently.
