### ISSUE TITLE
Membership Form

### ISSUE THREAD

**Issue by lynn-gavett** [megandalster/PQG-Website#19]
Linda and I tested the Membership form by sending in a test form.  I received the response email, which we need to change so checks are sent to our new PO Box 21558, HHI, SC 29925-1558.

Where does the application information go when it is completed?  Does it go to our PQG gmail?  How is the Member Directory updated?  I asked the person who monitors our gmail account to send me anything we received on my test, but she has not received anything.

The Membership form needs to be printable, and print to one page.

We may want to change the form, so I need to know how to do that.

**Comment by lynn-gavett** [comment]
Also, the PQG header and Menu should not be on Form page.

**Comment by megandalster** [comment]
This is redone now.  The completed form is printable and the new member should mail her application with a check to PQG.  No electronic stuff will happen in the background... too messy.  I will write an Editor Help instruction for changing the Membership form
