### ISSUE TITLE
Fix slider on home page so that it doesn't go back and forth and wiggle

### ISSUE THREAD

**Issue by megandalster** [megandalster/PQG-Website#2]

**Comment by lynn-gavett** [comment]
Is it possible to have the quilts fade in and out like the one sample website you sent us to look at initially?

**Comment by megandalster** [comment]
Not without paying more money.  

I have changed this a bit so that the quilts slide to the right and don't wiggle back and forth.  Since there are only a few slides in the group that's showing, the quilts slide back to the left when the end is reached. So it looks like the slider is going back and forth.  You can fix this by adding a lot roe quilts to the group (i'll write up an Editor Help instruction for doing this.)  For example, if you had 50 quilts in the group, it would only slide all the way back to the left when you get to the end of the 50.  Does that make sense?

**Comment by lynn-gavett** [comment]
Adding more quilts should work.  I need to crop and clean up the photos, so I will work at it.

**Comment by megandalster** [comment]
I have added an instruction to Editor Help called "Editing Front Page Slider and Colors" which shows you how to add and remove images from the slider.  Let me know how this works for you.

**Comment by megandalster** [comment]
I have added more details to this instruction that explains how the next Membership Meeting automatically goes to the front page, and also how to add another news item to the front page.
