### ISSUE TITLE
Home Page - Photo Bar

### ISSUE THREAD

**Issue by lynn-gavett** [megandalster/PQG-Website#20]
Linda is bother by the speed of the quilt photos moving across the page, and really hates the way it "swooshes" back to the beginning.  Can it fade, and not scroll?  If not, can we make it not fly back to the beginning, once it hits the last photo?  We both would prefer a fade.

**Comment by megandalster** [comment]
The photos now fade in groups of 4.  Each group of 4 is a separate image in the media library.  I have rewritten the instructions for editing these home page photos so that you can add new ones in the future.
