### ISSUE TITLE
Gallery Page

### ISSUE THREAD

**Issue by lynn-gavett** [megandalster/PQG-Website#23]
Since the Quilt Gallery Page photos are the same as the photos on the Home page Quilt Bar, we think the Gallery page should be a link to specific photo galleries, such as Show & Tell, 2016 Quilt Show, 2014 Quilt Show, Past Quilt Shows, etc.  

I showed the same items as subcategories of the Quilt Gallery tab on the Menu Bar.  The different galleries can be treated either way.  I suspect changing or adding galleries would be eaiser as links than as subcategories on the Menu Bar, but we can discuss.

**Comment by megandalster** [comment]
I've created new media categories 2014 Quilt Show, 2016 Quilt Show, Other Quilt Shows, and Show and Tell.  The Quilt Shows link now shows these categories as separate pages.  So when you create new media, put it into one of these new categories and it will show up on the right page.
