### ISSUE TITLE
More color

### ISSUE THREAD

**Issue by lynn-gavett** [megandalster/PQG-Website#4]
Linda and I both feel the pages are too white.  We discussed adding a background color to the Upcoming Events box on the right of the Home Page.  Is this something I can do?

**Comment by megandalster** [comment]
I have added color and a fine line border around the Upcoming Events box on the right.  To pick a different color, visit http://www.w3schools.com/colors/colors_picker.asp and let me know which one you want -- I can easily change the color.  (To do this yourself would require some comfort of CSS, which I'm not sure you want to learn ... let me know if I am incorrect and I'll be happy to show you how to manage the CSS coloring yourself.)

**Comment by lynn-gavett** [comment]
We need to be able to change the colors, so you will need to show me how to manage CSS.

**Comment by megandalster** [comment]
I have added an instruction to the Editor Help menu called "Editing Front Page Slider and Colors" which shows you how to mange the CSS and change colors.
