### ISSUE TITLE
Membership page

### ISSUE THREAD

**Issue by lynn-gavett** [megandalster/PQG-Website#7]
Thanks for the start on the membership page.  I will work on it.  It is my understanding that we only want the Membership Chairman to edit the membership information, so I will delete that reference.

**Comment by megandalster** [comment]
I have removed the capability for a member to edit her own contact information.

**Comment by megandalster** [comment]
I have added instructions under Editor Help for the Membership Chairman to add and edit each member's address, phone, and other contact information.
