### ISSUE TITLE
Media Library

### ISSUE THREAD

**Issue by lynn-gavett** [megandalster/PQG-Website#8]
There needs to be some organization to the Media Library.  Right now, you can view All Media Items, or view Images.  As we add newsletters and more photos, we will need more of a filing cabinet, so we can view just newletters, Show & Tell, "Quilt Show, etc.  Aslo, as we add newsletters, financial information, minutes, and other information, they wil need to be organized first by year.  Is that possible?

**Comment by megandalster** [comment]
I have begun to categorize the media in the Media Library.  Take a look at the new Editor Help page "Adding Images and Other Media" which describes the Media Categories and how to categorize a new item, and how to view only the media in a certain category.   Also, all media are date-stamped with the date they are created, so this will give us a handle on organizing them by year and month.  Notice that you can filter the media by date (Year and Month) and by Media Category.  Of course, we can change the categories as needed.

**Comment by megandalster** [comment]
It would be good at this point review the media categories and add new ones to cover financial information, minutes, etc. that should be uploaded and become available to the members under the Membership tab.
