### ISSUE TITLE
Quilt Show page & font

### ISSUE THREAD

**Issue by lynn-gavett** [megandalster/PQG-Website#9]
The font, used on the Quilt Show edit page, is not the font that appears on the Quilt Show web page?  
Also, could you move the Countdown Clock to the left of the page?  Or put it in on the right side of the Banner which says Quilt Show on the left?  Put "Only" and "remain until the"  to the right and left of the clock.

**Comment by megandalster** [comment]
I have restyled the countdown clock and moved it to the left of the page.  The font on that page is now all the same.

**Comment by lynn-gavett** [comment]
The clock is still too big.  Just a small rectangular box on the upper left page.  It is fun, but it is a gimmick.  When we start adding information about the Quilt Show, we will want the space for copy.

**Comment by megandalster** [comment]
I changed it.  Take a look and let me know.

**Comment by lynn-gavett** [comment]
Still too big.  Just want a small clock in upper right or left.

**Comment by megandalster** [comment]
It's smaller now and on the upper right.
